### ISSUE TITLE
Add link to check-more-types

### ISSUE THREAD

**Issue by bahmutov** [philbooth/check-types.js#24]
We have open sourced a few additional checks as [check-more-types](https://github.com/kensho/check-more-types). It would be nice if we could use something to extend check object (and get modifiers automatically) like `_.mixin`

**Comment by philbooth** [comment]
Hey @bahmutov, I've just been reminded of this one again.

I realise this is very late to be getting round to it, but can you spec the interface for me? What is the signature of the function that you'd like to call?

**Comment by bahmutov** [comment]
So in our check-more-types I have `check.mixin` function https://github.com/kensho/check-more-types#adding-your-own-predicates for quickly adding user's own predicates (including modifiers). It could be part of check-types (or not).

**Comment by philbooth** [comment]
Ah, okay. So just to be sure I understand correctly, are you saying that the function works as you want into from inside `check-more-types`? If so, it seems best to keep it there rather than add more weight to this library, right?

Or have I missed the point? Let me know if I'm wrong, otherwise I'll close this one.
