### ISSUE TITLE
instanceOf

### ISSUE THREAD

**Issue by derekdowling** [philbooth/check-types.js#38]
Is there any support for doing check.instanceOf(awesome, "Awesome")? I know you can accomplish this with plain old JS but it'd be nice to keep type checking consistent with only using this library.

**Comment by ceineke** [comment]
Are you asking if ```check.instance``` supports constructor functions designated by strings?

**Comment by philbooth** [comment]
As ceineke pointed out, there is an `instance` predicate for this (without the string bit). Closing this issue, but do please re-open it if I'm missing why that wouldn't work for you.

**Comment by euoia** [comment]
Hi @philbooth - thanks for this library.

I have found a case where check.instance doesn't agree with instanceof. In Chrome and Safari:
```
document.getElementById('el') instanceof HTMLElement
> true
```

But due to how the instance function in check-types.js checks that prototype is a function (see https://github.com/philbooth/check-types.js/blob/master/src/check-types.js#L151), the following returns false in Safari and true in Chrome:
```
check.assert.instance(document.getElementById('el'), HTMLElement);
```

Due to this behaviour in Safari:
```
typeof HTMLElement
> "object"
```

And this in Chrome:
```
typeof HTMLElement
> "function"
```

So although this seems due to a browser implementation difference, it is at least surprising that check.instance doesn't agree with instanceof. Is it necessary for the instance function to check that prototype is a function?

**Comment by philbooth** [comment]
Thanks for spotting this @euoia, I've raised it in a separate issue: #52.
