### ISSUE TITLE
Add synonyms nonempty*

### ISSUE THREAD

**Issue by dradetsky** [philbooth/check-types.js#45]
"unemptyString" is not canonical math-speak. it should be nonemptyString.

**Comment by philbooth** [comment]
Umm, thanks for your engaging and thoroughly considered proposal.

Let's look at the pros and the cons, as I see them:

## PROS

* It is "canonical math-speak", whatever that means.

## CONS

* It breaks the interface, forcing a major version change and existing users to update their usage.
* It's an extra character to type on each invocation.

## UNCLEAR EITHER WAY

* Which name is objectively better?
* Is anybody confused by the current predicate name?
* Would anybody be confused by the proposed new predicate name?

## VERDICT

Unfortunately , I do not "speak math". Perhaps if I did, I would understand the shining brilliance of your suggestion. But as it is, I don't see how this would add any value at all.

Sorry, won't fix. :)

**Comment by dradetsky** [comment]
It's not a huge problem, I'm just saying.

1. If I pull up the documentation, the first thing I'm going to search for
is 'nonempty string' because that's how that's referred to in math (and
computer science). I'll find 'unempty string' eventually, but it's not
standard terminology.

2. It doesn't have to break the interface. For example, you could add
`nonemptyString: unemptyString` to the predicates list (plus any other
bookkeeping* you hafta do). Then add 'nonemptyString: synonym for
unemptyString' to dox.

3. neither name is obviously objectively better, but more people will be
confused by 'unempty' than 'nonempty' if any are in fact confused.

**Comment by philbooth** [comment]
Re: 1. Fair enough, but that is indicative of an ongoing, greater problem with the documentation. It is too long and poorly structured. I tried to improve it previously by adding links to the top of the readme and then grouping predicates by the types on which they operate. But I need to do more. Fwiw, in this case, my hope would be that you see the "string predicates" link, click it and then find what you're looking for.

Re: 2. Synonyms in interfaces are an anti-pattern imho. Any time you have two names for the same thing and document the same thing in two places, you introduce the possibility of confusion and of them diverging. Granted, that seems extremely improbable in this case. But I dislike them generally and won't be introducing one here.

Re: 3. As someone who is neither a mathematician nor a computer scientist, evidently I've picked the wrong name. Apologies for getting it so wrong, but it's picked now and will remain until at least the next major rev. If I have cause to release a version 4, perhaps I'll come back to this.

**Comment by dradetsky** [comment]
understandable. i disagree with you about synonyms, but it's your library.
i suggest that you at least put the word 'nonempty' in the documentation
near the entry for 'unemptyString' and as comment in the code. (and similar
for objects, if you have that feature). like:

unemptyString
--------------------

AKA nonempty string. Matches...

or something.

**Comment by MareoRaft** [comment]
Hi Phil and dradetsky.  I'm sorry this conversation began in a negative way.  I would like to try to share an objective viewpoint.

"nonempty" is used in almost every field of mathematics to mean "not empty".  In fact, the prefix "non" is used universally in mathematics to mean "not", sometimes with a dash and sometimes without a dash.  I can only think of two times that "un" is used, and that is in the terms "unsatisfiable" and "undefined".  Moreover, "unempty" is not defined in English.

I understand that the switch could be a headache for users up front.  But consider that we have the opportunity to save far more headaches in the future, over time.

Here is just an idea of how you might make the switch:  What if make the unempty() methods methods which throw a helpful error message.  Something like "unempty has been renamed to nonempty.  You must replace methods with the term unempty in them with nonempty".

Well you give them a headache right up front.  But by forcing them to change sooner rather than later, you can fix the problem immediately and fully.

Thanks again for the great library.
-Mareo

**Comment by philbooth** [comment]
Consider `JSON.stringify`:

"Stringify" is not a word in the English language. The proper term that computer scientists understand is "serialize". Anyone coming to the ES spec and looking for the word "serialize" won't find it and will have headaches. Therefore TC39 should change the spec to `JSON.serialize` instead and it will save more headaches in the future. Do you agree?

I accept that, from your Maths/CS point of view, I picked the wrong name. But naming things is hard and people get it wrong all the time. A name is just a name at the end of the day.

As I already stated, if there is reason to break the interface in the future and release version 4, maybe I'll come back to this. But I don't think that changing the name of one predicate is sufficient grounds to release version 4 on its own. If I published a new major rev every time I wanted to tweak one thing in the interface, we'd probably be on version 104 by now. Consistency is in an important feature of a good interface imho, so breaking changes should be infrequent and exceptional.

**Comment by philbooth** [comment]
Also, if there is a problem of readability in your own code because, then of course there is nothing to stop you from forking and publishing you own version. In fact, I'd welcome it. All of my projects are [liberally licensed](https://github.com/philbooth/check-types.js/blob/master/COPYING) for precisely that reason.

So I definitely won't be offended if anybody wants to do that, please feel free. I wouldn't want my naming choices to cause you angst each time you read your own code! :)

**Comment by philbooth** [comment]
This has been fixed in version 4.0.0.
