### ISSUE TITLE
Object.prototype.toString used to check types?

### ISSUE THREAD

**Issue by MareoRaft** [philbooth/check-types.js#50]
I have a program that uses a custom object stringify function to allow me to debug things easier:

    Object.prototype.toString = function(){
        var string = '';
        for( var key in this )if( this.hasOwnProperty(key) ){
            var value = (typeof this[key] === 'number' || typeof this[key] === 'string'
                    || typeof this[key] === 'boolean' || Array.isArray(this[key]))?
                this[key].toString():
                    (typeof this[key] === 'undefined')?
                'undefined':
                'object';
            string += key + ': ' + value + '\n';
        }
        return string;
    };

It turns out this was causing check-types to fail on the assertion:

	check.assert.array.of.object(nodes)

Removing my custom stringification function caused the assertion to pass.  This leads me to believe that the check-types library is using the **toString** method in order to check types.  I feel this way of checking types can easily break and prevents me from debugging normally.  Can dependency on the **toString** method be removed?

**Comment by philbooth** [comment]
The reason we use `toString` is because `instanceof` does not work across frame boundaries. `toString` is a pretty commonly accepted workaround to that issue.

I'd also note that many people consider overriding prototype properties of JS built-ins as something of an anti-pattern, for precisely this kind of reason. Many, many libraries out there depend on their behaviour being as defined. If you change the behaviour, you do so at your own risk.

Therefore I don't see this issue being fixed. Sorry to disappoint. :-/
