### ISSUE TITLE
more robust check.instance()

### ISSUE THREAD

**Issue by MareoRaft** [philbooth/check-types.js#61]
Phil,

I am very happy with

    check.instance(c, Color)

for example, in most cases.  However, I was dismayed to see that

    check.instance("hello", String)

returned `false`.  I am aware that there is the shorter `check.string()` for scalars/primitives; however, I don't think this justifies `check.instance()` failing in those cases.  It is possible a programmer may decide to use `check.instance()` in all cases for consistency.  Also, users of check-types probably expect more robustness in general: this is the benefit of using a third party library over the built-in javascript functions.

I found the explanation by Jason Bunting to be helpful on this matter: http://stackoverflow.com/questions/332422/how-do-i-get-the-name-of-an-objects-type-in-javascript

Happy Coding! :)
-Mareo

**Comment by philbooth** [comment]
Hey Mareo.

So, there is a bit of history here and the `instance` function actually changed to its current behaviour [quite recently](https://github.com/philbooth/check-types.js/commit/8bc74ca7a6b284a209620c5d338aab175a114508).

The intention was that the different ways of identifying the type of an object should be split out to separate predicates, [`userDefined`](https://github.com/philbooth/check-types.js/blob/master/src/check-types.js#L377-L391) and [`builtIn`](https://github.com/philbooth/check-types.js/blob/master/src/check-types.js#L361-L375), and that these would separately cater for the different use-cases outlined in that StackOverflow answer you linked to. I even toyed with removing `instance` entirely for that reason, since it's covered by the other two functions now and probably confuses things in the documentation.

So there are four options:

1. Delete `instance`, then improve the documentation / naming for `builtIn` and `userDefined`.

2. Delete `builtIn` and `userDefined`, then change `instance` to fall back through both approaches.

3. Retain all three predicates as they are, but improve the documentation / naming to more clearly point out how they work and which to use in each case.

4. Retain all three predicates, but change `instance` so that it falls back to using the two other approaches.

Originally, I went for `3` on the grounds of efficiency and simplicity. My thinking was that a caller should always know which check they mean to use and they should not be forced to pay the price of unnecessary checks.

But perhaps option `4` or option `2` is better? I'm not sure which I prefer yet, what do you think?

**Comment by philbooth** [comment]
Actually, I'm starting to think I prefer option `1`.

**Comment by MareoRaft** [comment]
Currently, is `check.instance()` equivalent to using `instanceof` ?

**Comment by philbooth** [comment]
> Currently, is `check.instance()` equivalent to using `instanceof` ?

[Yep](https://github.com/philbooth/check-types.js/blob/master/src/check-types.js#L348-L359).

**Comment by MareoRaft** [comment]
Sorry, see my edit above.  So it seems they are a little different:

    function instance (object, prototype) {
             try {
                 return object instanceof prototype;
             } catch (error) {
                 return false;
             }
         }

I did not expect this behavior as a user.  Also, I'm wondering if there are good use cases where this behavior would be desirable.

I think information that would target the essence of the issue is the following:  

Is there a situation where a programmer would want `check.instance("hi", String)` to return false?

Does it make sense for something like `check.instance(a, Apple)` to return true AND `check.instance(a, Object)` to return true at the same time?  Is this related to our issue?

**Comment by MareoRaft** [comment]
I think it would also be extremely useful to think of a single example where `builtIn` and `userDefined` give different outputs, but both outputs are reasonable and desirable for some situation(s).

**Comment by philbooth** [comment]
I finally made my mind about this. In version `7.0.0`, published just now, the old `instance` predicate (which only tested `instanceof`) has been renamed to `instanceStrict` and the two old `builtIn` and `userDefined` predicates have been combined into a new `instance` predicate.

Closing this.
