### ISSUE TITLE
Request for check.defined method

### ISSUE THREAD

**Issue by MareoRaft** [philbooth/check-types.js#79]
This is a feature request.

Can we have a `check.defined` method that is equivalent to `!check.undefined`?

I realize that there used to be such a thing, and *not* a `check.undefined`.  I am asking if we can have both.  This would improve my code readability, and make it easier to parse the logic in my code.

All the best,
Matt

**Comment by philbooth** [comment]
Hmm, my initial reaction is that `check.not.undefined` already has this covered.

If we add an antonym for this case it opens the door to adding them for other cases, and I'd need to be persuaded they provide genuine utility in order to increase the API surface area like that. But maybe I'm missing something, you're welcome to try and persuade me otherwise if you have a concrete example of the improvement you think this brings?

**Comment by MareoRaft** [comment]
The only advantages I can think of are:

1. code readability
2. easier for human brains to parse
3. shorter

example:

    			if( is.not.undefined(dependency_node) ){
    				return dependency_id
    			}

vs

    			if( is.defined(dependency_node) ){
    				return dependency_id
    			}


But I understand why you prefer to have just one command.  I will close the issue but feel free to reopen.
