### ISSUE TITLE
Examples of "batch" checking?

### ISSUE THREAD

**Issue by grokky1** [philbooth/check-types.js#82]
It would have been great to have a fluent/chaining syntax like 

`checkString("abc123").contains("abc").not.contains("foo")`

But I see that this is [not supported](https://github.com/philbooth/check-types.js/issues/60).

The recommendation is to use "batch" operation. Are there examples of that?

**Comment by philbooth** [comment]
> It would have been great to have a fluent/chaining syntax like 
>
> `checkString("abc123").contains("abc").not.contains("foo")`
>
> But I see that this is [not supported](https://github.com/philbooth/check-types.js/issues/60).

Yep. Just a quick note on why it's not supported...

Most of the functions exported by `check-types` are predicates, returning either true or false. Obviously fluent interfaces work by returning `this` or some other context object, which means in your snippet above `contains` is no longer a predicate.

So to implement a fluent interface for `check-types`, we'd need to store the progressive results in the context object and then force callers to make an extra call to access the aggregate result when they're done. It's something I considered briefly but decided against because the benefit didn't seem to justify the additional burden to callers, many of whom may not be using the fluent parts of the interface.

> The recommendation is to use "batch" operation. Are there examples of that?

In the case of your snippet above, the batch functions aren't really suitable. Instead you just need to use ordinary logical operators to combine results:

```js
check.contains("abc123", "abc") && check.not.contains("abc123", "foo")
```

The batch functionality mentioned is for when you want to apply predicates to many values, either stored in an array or as properties on an object. The two batch operations are `apply` and `map`.

* `apply` executes a predicate or predicates against an array of values.

  ```js
  check.apply([ 1, 2, 3 ], check.odd);
  // returns [ true, false, true ]

  check.apply([ 1, 2, 3 ], [ check.odd, check.even, check.odd ]);
  // returns [ true, true, true ]
  ```

* `map` is similar but operates over an object's values:

  ```js
  check.map({ foo: "wibble", bar: "", baz: "blee" }, check.nonEmptyString);
  // returns { foo: true, bar: false, baz: true }

  check.map(
    { foo: "wibble", bar: "", baz: "blee" },
    { foo: check.nonEmptyString, bar: check.emptyString, baz: check.nonEmptyString }
  );
  // returns { foo: true, bar: true, baz: true }
  ```

To make it easier to use `apply` and `map`, there are two helpers for aggregating their results: `any` and `all`.

* `any` returns true if any value in an array, or any property in an object, is true.

  ```js
  check.any([ false, false ]);
  // returns false

  check.any([ false, true ]);
  // returns true

  check.any({ foo: false, bar: false });
  // returns false

  check.any({ foo: false, bar: true });
  // returns true
  ```

* `all` returns true if every value in an array, or every property in an object, is true.

  ```js
  check.all([ false, true ]);
  // returns false

  check.all([ true, true ]);
  // returns true

  check.all({ foo: false, bar: true });
  // returns false

  check.all({ foo: true, bar: true });
  // returns true
  ```

Putting that all together, you can pass the results `apply` and `map` directly to `any` and `all`:

```js
check.any(check.apply([ 1, 2, 3 ], check.odd));
// returns true

check.all(check.apply([ 1, 2, 3 ], check.odd));
// returns false

check.any(check.map({ foo: 1, bar: 2, baz: 3 }, check.odd));
// returns true

check.all(check.map({ foo: 1, bar: 2, baz: 3 }, check.odd));
// returns false
```

Does that make sense?
