### ISSUE TITLE
New ES6+ types

### ISSUE THREAD

**Issue by sp00m** [philbooth/check-types.js#84]
Could be nice to have checkers for new ES6+ types like `Map` or `Set`. What do you think?

**Comment by philbooth** [comment]
On the whole I've tried to avoid object-specific predicates like that to try and keep the library size as small as possible. You could achieve the same result by calling:

```js
check.instanceStrict(foo, Map)
```

Also note that there is a more general `check.iterable` predicate for all iterables, including `Map` and `Set`, if that is more what you're after.

So as it stands, I think I'm thumbs-down on this one. I'm happy to be persuaded otherwise though!

**Comment by sp00m** [comment]
I did not think about using `instanceStrict`, this will fit my needs.

Thanks for your feedback, keep up the great work!
