### ISSUE TITLE
Checks for promise status

### ISSUE THREAD

**Issue by Gipphe** [philbooth/check-types.js#89]
Not entirely the same as #85, mind you, but something along the lines of `check.fulfilledPromise`, `check.rejectedPromise` and `check.pendingPromise`. I know you are averse to object-specific checks, but considering how integrated Promises are in javascript nowadays, I'd say it's worth considering 👌

**Comment by philbooth** [comment]
@Gipphe, I'm not totally against this idea but I'm also not familiar enough with the minutiae of promises to know if there's a reliable cross-platform way to tackle it. It seems like something that might rely on implementation details and bear in mind we'd want it to work for library implementations like Bluebird et al, in addition native promises.

If you know some more about that, feel free to weigh in. Otherwise I can dig into it some more myself at the weekend.

**Comment by Gipphe** [comment]
This seems very brittle, if at all feasible. [The spec](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-constructor) specifies the `[[PromiseState]]` slot is an internal one, meaning it is entirely up to the specific implementation whether the state should be visible from the outside at all.
Given how these state properties (as is how they are usually handled) are not supposed to be available for public consumption, their specifics can change at any time, at any version bump whatsoever. Because of this, it is unfeasible to support these kind of checks, unfortunately. Unless you find something else to hatch onto for reliable state checks, you are free to close this Phil.

**Comment by Gipphe** [comment]
The usefulness of this is also somewhat arguable given how Promises are supposed to abstract away the need to check its state.

**Comment by philbooth** [comment]
No worries, thanks for taking the time to dig into it @Gipphe!
